// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: friend.proto

package com.jpush.protobuf;

public final class Friend {
  private Friend() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface AddFriendOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // repeated int64 friend_id = 1;
    /**
     * <code>repeated int64 friend_id = 1;</code>
     */
    java.util.List<java.lang.Long> getFriendIdList();
    /**
     * <code>repeated int64 friend_id = 1;</code>
     */
    int getFriendIdCount();
    /**
     * <code>repeated int64 friend_id = 1;</code>
     */
    long getFriendId(int index);

    // repeated string friend_name = 2;
    /**
     * <code>repeated string friend_name = 2;</code>
     */
    java.util.List<java.lang.String>
    getFriendNameList();
    /**
     * <code>repeated string friend_name = 2;</code>
     */
    int getFriendNameCount();
    /**
     * <code>repeated string friend_name = 2;</code>
     */
    java.lang.String getFriendName(int index);
    /**
     * <code>repeated string friend_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getFriendNameBytes(int index);
  }
  /**
   * Protobuf type {@code com.jpush.im.protobuf.AddFriend}
   *
   * <pre>
   * cmd = 5
   * </pre>
   */
  public static final class AddFriend extends
      com.google.protobuf.GeneratedMessageLite
      implements AddFriendOrBuilder {
    // Use AddFriend.newBuilder() to construct.
    private AddFriend(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private AddFriend(boolean noInit) {}

    private static final AddFriend defaultInstance;
    public static AddFriend getDefaultInstance() {
      return defaultInstance;
    }

    public AddFriend getDefaultInstanceForType() {
      return defaultInstance;
    }

    private AddFriend(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                friendId_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000001;
              }
              friendId_.add(input.readInt64());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                friendId_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                friendId_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                friendName_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              friendName_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          friendId_ = java.util.Collections.unmodifiableList(friendId_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          friendName_ = new com.google.protobuf.UnmodifiableLazyStringList(friendName_);
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<AddFriend> PARSER =
        new com.google.protobuf.AbstractParser<AddFriend>() {
      public AddFriend parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AddFriend(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AddFriend> getParserForType() {
      return PARSER;
    }

    // repeated int64 friend_id = 1;
    public static final int FRIEND_ID_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Long> friendId_;
    /**
     * <code>repeated int64 friend_id = 1;</code>
     */
    public java.util.List<java.lang.Long>
        getFriendIdList() {
      return friendId_;
    }
    /**
     * <code>repeated int64 friend_id = 1;</code>
     */
    public int getFriendIdCount() {
      return friendId_.size();
    }
    /**
     * <code>repeated int64 friend_id = 1;</code>
     */
    public long getFriendId(int index) {
      return friendId_.get(index);
    }

    // repeated string friend_name = 2;
    public static final int FRIEND_NAME_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList friendName_;
    /**
     * <code>repeated string friend_name = 2;</code>
     */
    public java.util.List<java.lang.String>
        getFriendNameList() {
      return friendName_;
    }
    /**
     * <code>repeated string friend_name = 2;</code>
     */
    public int getFriendNameCount() {
      return friendName_.size();
    }
    /**
     * <code>repeated string friend_name = 2;</code>
     */
    public java.lang.String getFriendName(int index) {
      return friendName_.get(index);
    }
    /**
     * <code>repeated string friend_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFriendNameBytes(int index) {
      return friendName_.getByteString(index);
    }

    private void initFields() {
      friendId_ = java.util.Collections.emptyList();
      friendName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < friendId_.size(); i++) {
        output.writeInt64(1, friendId_.get(i));
      }
      for (int i = 0; i < friendName_.size(); i++) {
        output.writeBytes(2, friendName_.getByteString(i));
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < friendId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(friendId_.get(i));
        }
        size += dataSize;
        size += 1 * getFriendIdList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < friendName_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(friendName_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getFriendNameList().size();
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.jpush.protobuf.Friend.AddFriend parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jpush.protobuf.Friend.AddFriend parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jpush.protobuf.Friend.AddFriend parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jpush.protobuf.Friend.AddFriend parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jpush.protobuf.Friend.AddFriend parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jpush.protobuf.Friend.AddFriend parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.jpush.protobuf.Friend.AddFriend parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.jpush.protobuf.Friend.AddFriend parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.jpush.protobuf.Friend.AddFriend parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jpush.protobuf.Friend.AddFriend parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.jpush.protobuf.Friend.AddFriend prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code com.jpush.im.protobuf.AddFriend}
     *
     * <pre>
     * cmd = 5
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.jpush.protobuf.Friend.AddFriend, Builder>
        implements com.jpush.protobuf.Friend.AddFriendOrBuilder {
      // Construct using com.jpush.im.protobuf.Friend.AddFriend.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        friendId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        friendName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.jpush.protobuf.Friend.AddFriend getDefaultInstanceForType() {
        return com.jpush.protobuf.Friend.AddFriend.getDefaultInstance();
      }

      public com.jpush.protobuf.Friend.AddFriend build() {
        com.jpush.protobuf.Friend.AddFriend result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.jpush.protobuf.Friend.AddFriend buildPartial() {
        com.jpush.protobuf.Friend.AddFriend result = new com.jpush.protobuf.Friend.AddFriend(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          friendId_ = java.util.Collections.unmodifiableList(friendId_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.friendId_ = friendId_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          friendName_ = new com.google.protobuf.UnmodifiableLazyStringList(
              friendName_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.friendName_ = friendName_;
        return result;
      }

      public Builder mergeFrom(com.jpush.protobuf.Friend.AddFriend other) {
        if (other == com.jpush.protobuf.Friend.AddFriend.getDefaultInstance()) return this;
        if (!other.friendId_.isEmpty()) {
          if (friendId_.isEmpty()) {
            friendId_ = other.friendId_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureFriendIdIsMutable();
            friendId_.addAll(other.friendId_);
          }
          
        }
        if (!other.friendName_.isEmpty()) {
          if (friendName_.isEmpty()) {
            friendName_ = other.friendName_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureFriendNameIsMutable();
            friendName_.addAll(other.friendName_);
          }
          
        }
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jpush.protobuf.Friend.AddFriend parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jpush.protobuf.Friend.AddFriend) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated int64 friend_id = 1;
      private java.util.List<java.lang.Long> friendId_ = java.util.Collections.emptyList();
      private void ensureFriendIdIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          friendId_ = new java.util.ArrayList<java.lang.Long>(friendId_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int64 friend_id = 1;</code>
       */
      public java.util.List<java.lang.Long>
          getFriendIdList() {
        return java.util.Collections.unmodifiableList(friendId_);
      }
      /**
       * <code>repeated int64 friend_id = 1;</code>
       */
      public int getFriendIdCount() {
        return friendId_.size();
      }
      /**
       * <code>repeated int64 friend_id = 1;</code>
       */
      public long getFriendId(int index) {
        return friendId_.get(index);
      }
      /**
       * <code>repeated int64 friend_id = 1;</code>
       */
      public Builder setFriendId(
          int index, long value) {
        ensureFriendIdIsMutable();
        friendId_.set(index, value);
        
        return this;
      }
      /**
       * <code>repeated int64 friend_id = 1;</code>
       */
      public Builder addFriendId(long value) {
        ensureFriendIdIsMutable();
        friendId_.add(value);
        
        return this;
      }
      /**
       * <code>repeated int64 friend_id = 1;</code>
       */
      public Builder addAllFriendId(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureFriendIdIsMutable();
        super.addAll(values, friendId_);
        
        return this;
      }
      /**
       * <code>repeated int64 friend_id = 1;</code>
       */
      public Builder clearFriendId() {
        friendId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        
        return this;
      }

      // repeated string friend_name = 2;
      private com.google.protobuf.LazyStringList friendName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureFriendNameIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          friendName_ = new com.google.protobuf.LazyStringArrayList(friendName_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string friend_name = 2;</code>
       */
      public java.util.List<java.lang.String>
          getFriendNameList() {
        return java.util.Collections.unmodifiableList(friendName_);
      }
      /**
       * <code>repeated string friend_name = 2;</code>
       */
      public int getFriendNameCount() {
        return friendName_.size();
      }
      /**
       * <code>repeated string friend_name = 2;</code>
       */
      public java.lang.String getFriendName(int index) {
        return friendName_.get(index);
      }
      /**
       * <code>repeated string friend_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFriendNameBytes(int index) {
        return friendName_.getByteString(index);
      }
      /**
       * <code>repeated string friend_name = 2;</code>
       */
      public Builder setFriendName(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFriendNameIsMutable();
        friendName_.set(index, value);
        
        return this;
      }
      /**
       * <code>repeated string friend_name = 2;</code>
       */
      public Builder addFriendName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFriendNameIsMutable();
        friendName_.add(value);
        
        return this;
      }
      /**
       * <code>repeated string friend_name = 2;</code>
       */
      public Builder addAllFriendName(
          java.lang.Iterable<java.lang.String> values) {
        ensureFriendNameIsMutable();
        super.addAll(values, friendName_);
        
        return this;
      }
      /**
       * <code>repeated string friend_name = 2;</code>
       */
      public Builder clearFriendName() {
        friendName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        
        return this;
      }
      /**
       * <code>repeated string friend_name = 2;</code>
       */
      public Builder addFriendNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFriendNameIsMutable();
        friendName_.add(value);
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.jpush.im.protobuf.AddFriend)
    }

    static {
      defaultInstance = new AddFriend(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.jpush.im.protobuf.AddFriend)
  }

  public interface DelFriendOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // optional int64 friend_id = 1;
    /**
     * <code>optional int64 friend_id = 1;</code>
     */
    boolean hasFriendId();
    /**
     * <code>optional int64 friend_id = 1;</code>
     */
    long getFriendId();
  }
  /**
   * Protobuf type {@code com.jpush.im.protobuf.DelFriend}
   *
   * <pre>
   * cmd = 6
   * </pre>
   */
  public static final class DelFriend extends
      com.google.protobuf.GeneratedMessageLite
      implements DelFriendOrBuilder {
    // Use DelFriend.newBuilder() to construct.
    private DelFriend(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private DelFriend(boolean noInit) {}

    private static final DelFriend defaultInstance;
    public static DelFriend getDefaultInstance() {
      return defaultInstance;
    }

    public DelFriend getDefaultInstanceForType() {
      return defaultInstance;
    }

    private DelFriend(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              friendId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<DelFriend> PARSER =
        new com.google.protobuf.AbstractParser<DelFriend>() {
      public DelFriend parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DelFriend(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DelFriend> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 friend_id = 1;
    public static final int FRIEND_ID_FIELD_NUMBER = 1;
    private long friendId_;
    /**
     * <code>optional int64 friend_id = 1;</code>
     */
    public boolean hasFriendId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 friend_id = 1;</code>
     */
    public long getFriendId() {
      return friendId_;
    }

    private void initFields() {
      friendId_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, friendId_);
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, friendId_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.jpush.protobuf.Friend.DelFriend parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jpush.protobuf.Friend.DelFriend parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jpush.protobuf.Friend.DelFriend parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jpush.protobuf.Friend.DelFriend parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jpush.protobuf.Friend.DelFriend parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jpush.protobuf.Friend.DelFriend parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.jpush.protobuf.Friend.DelFriend parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.jpush.protobuf.Friend.DelFriend parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.jpush.protobuf.Friend.DelFriend parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jpush.protobuf.Friend.DelFriend parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.jpush.protobuf.Friend.DelFriend prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code com.jpush.im.protobuf.DelFriend}
     *
     * <pre>
     * cmd = 6
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.jpush.protobuf.Friend.DelFriend, Builder>
        implements com.jpush.protobuf.Friend.DelFriendOrBuilder {
      // Construct using com.jpush.im.protobuf.Friend.DelFriend.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        friendId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.jpush.protobuf.Friend.DelFriend getDefaultInstanceForType() {
        return com.jpush.protobuf.Friend.DelFriend.getDefaultInstance();
      }

      public com.jpush.protobuf.Friend.DelFriend build() {
        com.jpush.protobuf.Friend.DelFriend result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.jpush.protobuf.Friend.DelFriend buildPartial() {
        com.jpush.protobuf.Friend.DelFriend result = new com.jpush.protobuf.Friend.DelFriend(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.friendId_ = friendId_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.jpush.protobuf.Friend.DelFriend other) {
        if (other == com.jpush.protobuf.Friend.DelFriend.getDefaultInstance()) return this;
        if (other.hasFriendId()) {
          setFriendId(other.getFriendId());
        }
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jpush.protobuf.Friend.DelFriend parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jpush.protobuf.Friend.DelFriend) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 friend_id = 1;
      private long friendId_ ;
      /**
       * <code>optional int64 friend_id = 1;</code>
       */
      public boolean hasFriendId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 friend_id = 1;</code>
       */
      public long getFriendId() {
        return friendId_;
      }
      /**
       * <code>optional int64 friend_id = 1;</code>
       */
      public Builder setFriendId(long value) {
        bitField0_ |= 0x00000001;
        friendId_ = value;
        
        return this;
      }
      /**
       * <code>optional int64 friend_id = 1;</code>
       */
      public Builder clearFriendId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        friendId_ = 0L;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.jpush.im.protobuf.DelFriend)
    }

    static {
      defaultInstance = new DelFriend(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.jpush.im.protobuf.DelFriend)
  }

  public interface UpdateMemoOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // optional int64 friend_id = 1;
    /**
     * <code>optional int64 friend_id = 1;</code>
     */
    boolean hasFriendId();
    /**
     * <code>optional int64 friend_id = 1;</code>
     */
    long getFriendId();

    // optional string memo_name = 2;
    /**
     * <code>optional string memo_name = 2;</code>
     */
    boolean hasMemoName();
    /**
     * <code>optional string memo_name = 2;</code>
     */
    java.lang.String getMemoName();
    /**
     * <code>optional string memo_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getMemoNameBytes();

    // optional string memo_text = 3;
    /**
     * <code>optional string memo_text = 3;</code>
     */
    boolean hasMemoText();
    /**
     * <code>optional string memo_text = 3;</code>
     */
    java.lang.String getMemoText();
    /**
     * <code>optional string memo_text = 3;</code>
     */
    com.google.protobuf.ByteString
        getMemoTextBytes();
  }
  /**
   * Protobuf type {@code com.jpush.im.protobuf.UpdateMemo}
   *
   * <pre>
   * cmd = 7
   * </pre>
   */
  public static final class UpdateMemo extends
      com.google.protobuf.GeneratedMessageLite
      implements UpdateMemoOrBuilder {
    // Use UpdateMemo.newBuilder() to construct.
    private UpdateMemo(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private UpdateMemo(boolean noInit) {}

    private static final UpdateMemo defaultInstance;
    public static UpdateMemo getDefaultInstance() {
      return defaultInstance;
    }

    public UpdateMemo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private UpdateMemo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              friendId_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              memoName_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              memoText_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<UpdateMemo> PARSER =
        new com.google.protobuf.AbstractParser<UpdateMemo>() {
      public UpdateMemo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UpdateMemo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<UpdateMemo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 friend_id = 1;
    public static final int FRIEND_ID_FIELD_NUMBER = 1;
    private long friendId_;
    /**
     * <code>optional int64 friend_id = 1;</code>
     */
    public boolean hasFriendId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 friend_id = 1;</code>
     */
    public long getFriendId() {
      return friendId_;
    }

    // optional string memo_name = 2;
    public static final int MEMO_NAME_FIELD_NUMBER = 2;
    private java.lang.Object memoName_;
    /**
     * <code>optional string memo_name = 2;</code>
     */
    public boolean hasMemoName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string memo_name = 2;</code>
     */
    public java.lang.String getMemoName() {
      java.lang.Object ref = memoName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          memoName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string memo_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMemoNameBytes() {
      java.lang.Object ref = memoName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        memoName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string memo_text = 3;
    public static final int MEMO_TEXT_FIELD_NUMBER = 3;
    private java.lang.Object memoText_;
    /**
     * <code>optional string memo_text = 3;</code>
     */
    public boolean hasMemoText() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string memo_text = 3;</code>
     */
    public java.lang.String getMemoText() {
      java.lang.Object ref = memoText_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          memoText_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string memo_text = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMemoTextBytes() {
      java.lang.Object ref = memoText_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        memoText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      friendId_ = 0L;
      memoName_ = "";
      memoText_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, friendId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMemoNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getMemoTextBytes());
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, friendId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMemoNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getMemoTextBytes());
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.jpush.protobuf.Friend.UpdateMemo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jpush.protobuf.Friend.UpdateMemo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jpush.protobuf.Friend.UpdateMemo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jpush.protobuf.Friend.UpdateMemo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jpush.protobuf.Friend.UpdateMemo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jpush.protobuf.Friend.UpdateMemo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.jpush.protobuf.Friend.UpdateMemo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.jpush.protobuf.Friend.UpdateMemo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.jpush.protobuf.Friend.UpdateMemo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jpush.protobuf.Friend.UpdateMemo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.jpush.protobuf.Friend.UpdateMemo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code com.jpush.im.protobuf.UpdateMemo}
     *
     * <pre>
     * cmd = 7
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.jpush.protobuf.Friend.UpdateMemo, Builder>
        implements com.jpush.protobuf.Friend.UpdateMemoOrBuilder {
      // Construct using com.jpush.im.protobuf.Friend.UpdateMemo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        friendId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        memoName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        memoText_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.jpush.protobuf.Friend.UpdateMemo getDefaultInstanceForType() {
        return com.jpush.protobuf.Friend.UpdateMemo.getDefaultInstance();
      }

      public com.jpush.protobuf.Friend.UpdateMemo build() {
        com.jpush.protobuf.Friend.UpdateMemo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.jpush.protobuf.Friend.UpdateMemo buildPartial() {
        com.jpush.protobuf.Friend.UpdateMemo result = new com.jpush.protobuf.Friend.UpdateMemo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.friendId_ = friendId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.memoName_ = memoName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.memoText_ = memoText_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.jpush.protobuf.Friend.UpdateMemo other) {
        if (other == com.jpush.protobuf.Friend.UpdateMemo.getDefaultInstance()) return this;
        if (other.hasFriendId()) {
          setFriendId(other.getFriendId());
        }
        if (other.hasMemoName()) {
          bitField0_ |= 0x00000002;
          memoName_ = other.memoName_;
          
        }
        if (other.hasMemoText()) {
          bitField0_ |= 0x00000004;
          memoText_ = other.memoText_;
          
        }
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jpush.protobuf.Friend.UpdateMemo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jpush.protobuf.Friend.UpdateMemo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 friend_id = 1;
      private long friendId_ ;
      /**
       * <code>optional int64 friend_id = 1;</code>
       */
      public boolean hasFriendId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 friend_id = 1;</code>
       */
      public long getFriendId() {
        return friendId_;
      }
      /**
       * <code>optional int64 friend_id = 1;</code>
       */
      public Builder setFriendId(long value) {
        bitField0_ |= 0x00000001;
        friendId_ = value;
        
        return this;
      }
      /**
       * <code>optional int64 friend_id = 1;</code>
       */
      public Builder clearFriendId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        friendId_ = 0L;
        
        return this;
      }

      // optional string memo_name = 2;
      private java.lang.Object memoName_ = "";
      /**
       * <code>optional string memo_name = 2;</code>
       */
      public boolean hasMemoName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string memo_name = 2;</code>
       */
      public java.lang.String getMemoName() {
        java.lang.Object ref = memoName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          memoName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string memo_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMemoNameBytes() {
        java.lang.Object ref = memoName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          memoName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string memo_name = 2;</code>
       */
      public Builder setMemoName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        memoName_ = value;
        
        return this;
      }
      /**
       * <code>optional string memo_name = 2;</code>
       */
      public Builder clearMemoName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        memoName_ = getDefaultInstance().getMemoName();
        
        return this;
      }
      /**
       * <code>optional string memo_name = 2;</code>
       */
      public Builder setMemoNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        memoName_ = value;
        
        return this;
      }

      // optional string memo_text = 3;
      private java.lang.Object memoText_ = "";
      /**
       * <code>optional string memo_text = 3;</code>
       */
      public boolean hasMemoText() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string memo_text = 3;</code>
       */
      public java.lang.String getMemoText() {
        java.lang.Object ref = memoText_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          memoText_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string memo_text = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMemoTextBytes() {
        java.lang.Object ref = memoText_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          memoText_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string memo_text = 3;</code>
       */
      public Builder setMemoText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        memoText_ = value;
        
        return this;
      }
      /**
       * <code>optional string memo_text = 3;</code>
       */
      public Builder clearMemoText() {
        bitField0_ = (bitField0_ & ~0x00000004);
        memoText_ = getDefaultInstance().getMemoText();
        
        return this;
      }
      /**
       * <code>optional string memo_text = 3;</code>
       */
      public Builder setMemoTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        memoText_ = value;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.jpush.im.protobuf.UpdateMemo)
    }

    static {
      defaultInstance = new UpdateMemo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.jpush.im.protobuf.UpdateMemo)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
