// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: group.proto

package com.jpush.protobuf;

public final class Group {
  private Group() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface CreateGroupOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // optional string group_name = 1;
    /**
     * <code>optional string group_name = 1;</code>
     */
    boolean hasGroupName();
    /**
     * <code>optional string group_name = 1;</code>
     */
    java.lang.String getGroupName();
    /**
     * <code>optional string group_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getGroupNameBytes();

    // optional string group_desc = 2;
    /**
     * <code>optional string group_desc = 2;</code>
     */
    boolean hasGroupDesc();
    /**
     * <code>optional string group_desc = 2;</code>
     */
    java.lang.String getGroupDesc();
    /**
     * <code>optional string group_desc = 2;</code>
     */
    com.google.protobuf.ByteString
        getGroupDescBytes();

    // optional int32 group_level = 3;
    /**
     * <code>optional int32 group_level = 3;</code>
     */
    boolean hasGroupLevel();
    /**
     * <code>optional int32 group_level = 3;</code>
     */
    int getGroupLevel();

    // optional int32 flag = 4;
    /**
     * <code>optional int32 flag = 4;</code>
     */
    boolean hasFlag();
    /**
     * <code>optional int32 flag = 4;</code>
     */
    int getFlag();

    // optional int64 gid = 5;
    /**
     * <code>optional int64 gid = 5;</code>
     *
     * <pre>
     *for resp
     * </pre>
     */
    boolean hasGid();
    /**
     * <code>optional int64 gid = 5;</code>
     *
     * <pre>
     *for resp
     * </pre>
     */
    long getGid();
  }
  /**
   * Protobuf type {@code com.jpush.im.protobuf.CreateGroup}
   *
   * <pre>
   * cmd = 8
   * </pre>
   */
  public static final class CreateGroup extends
      com.google.protobuf.GeneratedMessageLite
      implements CreateGroupOrBuilder {
    // Use CreateGroup.newBuilder() to construct.
    private CreateGroup(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private CreateGroup(boolean noInit) {}

    private static final CreateGroup defaultInstance;
    public static CreateGroup getDefaultInstance() {
      return defaultInstance;
    }

    public CreateGroup getDefaultInstanceForType() {
      return defaultInstance;
    }

    private CreateGroup(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              groupName_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              groupDesc_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              groupLevel_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              flag_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              gid_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<CreateGroup> PARSER =
        new com.google.protobuf.AbstractParser<CreateGroup>() {
      public CreateGroup parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CreateGroup(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CreateGroup> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string group_name = 1;
    public static final int GROUP_NAME_FIELD_NUMBER = 1;
    private java.lang.Object groupName_;
    /**
     * <code>optional string group_name = 1;</code>
     */
    public boolean hasGroupName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string group_name = 1;</code>
     */
    public java.lang.String getGroupName() {
      java.lang.Object ref = groupName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          groupName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string group_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getGroupNameBytes() {
      java.lang.Object ref = groupName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        groupName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string group_desc = 2;
    public static final int GROUP_DESC_FIELD_NUMBER = 2;
    private java.lang.Object groupDesc_;
    /**
     * <code>optional string group_desc = 2;</code>
     */
    public boolean hasGroupDesc() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string group_desc = 2;</code>
     */
    public java.lang.String getGroupDesc() {
      java.lang.Object ref = groupDesc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          groupDesc_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string group_desc = 2;</code>
     */
    public com.google.protobuf.ByteString
        getGroupDescBytes() {
      java.lang.Object ref = groupDesc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        groupDesc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 group_level = 3;
    public static final int GROUP_LEVEL_FIELD_NUMBER = 3;
    private int groupLevel_;
    /**
     * <code>optional int32 group_level = 3;</code>
     */
    public boolean hasGroupLevel() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 group_level = 3;</code>
     */
    public int getGroupLevel() {
      return groupLevel_;
    }

    // optional int32 flag = 4;
    public static final int FLAG_FIELD_NUMBER = 4;
    private int flag_;
    /**
     * <code>optional int32 flag = 4;</code>
     */
    public boolean hasFlag() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 flag = 4;</code>
     */
    public int getFlag() {
      return flag_;
    }

    // optional int64 gid = 5;
    public static final int GID_FIELD_NUMBER = 5;
    private long gid_;
    /**
     * <code>optional int64 gid = 5;</code>
     *
     * <pre>
     *for resp
     * </pre>
     */
    public boolean hasGid() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int64 gid = 5;</code>
     *
     * <pre>
     *for resp
     * </pre>
     */
    public long getGid() {
      return gid_;
    }

    private void initFields() {
      groupName_ = "";
      groupDesc_ = "";
      groupLevel_ = 0;
      flag_ = 0;
      gid_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getGroupNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getGroupDescBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, groupLevel_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, flag_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, gid_);
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getGroupNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getGroupDescBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, groupLevel_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, flag_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, gid_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.jpush.protobuf.Group.CreateGroup parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jpush.protobuf.Group.CreateGroup parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jpush.protobuf.Group.CreateGroup parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jpush.protobuf.Group.CreateGroup parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jpush.protobuf.Group.CreateGroup parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jpush.protobuf.Group.CreateGroup parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.jpush.protobuf.Group.CreateGroup parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.jpush.protobuf.Group.CreateGroup parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.jpush.protobuf.Group.CreateGroup parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jpush.protobuf.Group.CreateGroup parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.jpush.protobuf.Group.CreateGroup prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code com.jpush.im.protobuf.CreateGroup}
     *
     * <pre>
     * cmd = 8
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.jpush.protobuf.Group.CreateGroup, Builder>
        implements com.jpush.protobuf.Group.CreateGroupOrBuilder {
      // Construct using com.jpush.im.protobuf.Group.CreateGroup.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        groupName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        groupDesc_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        groupLevel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        flag_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        gid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.jpush.protobuf.Group.CreateGroup getDefaultInstanceForType() {
        return com.jpush.protobuf.Group.CreateGroup.getDefaultInstance();
      }

      public com.jpush.protobuf.Group.CreateGroup build() {
        com.jpush.protobuf.Group.CreateGroup result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.jpush.protobuf.Group.CreateGroup buildPartial() {
        com.jpush.protobuf.Group.CreateGroup result = new com.jpush.protobuf.Group.CreateGroup(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.groupName_ = groupName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.groupDesc_ = groupDesc_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.groupLevel_ = groupLevel_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.flag_ = flag_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.gid_ = gid_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.jpush.protobuf.Group.CreateGroup other) {
        if (other == com.jpush.protobuf.Group.CreateGroup.getDefaultInstance()) return this;
        if (other.hasGroupName()) {
          bitField0_ |= 0x00000001;
          groupName_ = other.groupName_;
          
        }
        if (other.hasGroupDesc()) {
          bitField0_ |= 0x00000002;
          groupDesc_ = other.groupDesc_;
          
        }
        if (other.hasGroupLevel()) {
          setGroupLevel(other.getGroupLevel());
        }
        if (other.hasFlag()) {
          setFlag(other.getFlag());
        }
        if (other.hasGid()) {
          setGid(other.getGid());
        }
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jpush.protobuf.Group.CreateGroup parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jpush.protobuf.Group.CreateGroup) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string group_name = 1;
      private java.lang.Object groupName_ = "";
      /**
       * <code>optional string group_name = 1;</code>
       */
      public boolean hasGroupName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string group_name = 1;</code>
       */
      public java.lang.String getGroupName() {
        java.lang.Object ref = groupName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          groupName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string group_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getGroupNameBytes() {
        java.lang.Object ref = groupName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          groupName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string group_name = 1;</code>
       */
      public Builder setGroupName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        groupName_ = value;
        
        return this;
      }
      /**
       * <code>optional string group_name = 1;</code>
       */
      public Builder clearGroupName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        groupName_ = getDefaultInstance().getGroupName();
        
        return this;
      }
      /**
       * <code>optional string group_name = 1;</code>
       */
      public Builder setGroupNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        groupName_ = value;
        
        return this;
      }

      // optional string group_desc = 2;
      private java.lang.Object groupDesc_ = "";
      /**
       * <code>optional string group_desc = 2;</code>
       */
      public boolean hasGroupDesc() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string group_desc = 2;</code>
       */
      public java.lang.String getGroupDesc() {
        java.lang.Object ref = groupDesc_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          groupDesc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string group_desc = 2;</code>
       */
      public com.google.protobuf.ByteString
          getGroupDescBytes() {
        java.lang.Object ref = groupDesc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          groupDesc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string group_desc = 2;</code>
       */
      public Builder setGroupDesc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        groupDesc_ = value;
        
        return this;
      }
      /**
       * <code>optional string group_desc = 2;</code>
       */
      public Builder clearGroupDesc() {
        bitField0_ = (bitField0_ & ~0x00000002);
        groupDesc_ = getDefaultInstance().getGroupDesc();
        
        return this;
      }
      /**
       * <code>optional string group_desc = 2;</code>
       */
      public Builder setGroupDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        groupDesc_ = value;
        
        return this;
      }

      // optional int32 group_level = 3;
      private int groupLevel_ ;
      /**
       * <code>optional int32 group_level = 3;</code>
       */
      public boolean hasGroupLevel() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 group_level = 3;</code>
       */
      public int getGroupLevel() {
        return groupLevel_;
      }
      /**
       * <code>optional int32 group_level = 3;</code>
       */
      public Builder setGroupLevel(int value) {
        bitField0_ |= 0x00000004;
        groupLevel_ = value;
        
        return this;
      }
      /**
       * <code>optional int32 group_level = 3;</code>
       */
      public Builder clearGroupLevel() {
        bitField0_ = (bitField0_ & ~0x00000004);
        groupLevel_ = 0;
        
        return this;
      }

      // optional int32 flag = 4;
      private int flag_ ;
      /**
       * <code>optional int32 flag = 4;</code>
       */
      public boolean hasFlag() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 flag = 4;</code>
       */
      public int getFlag() {
        return flag_;
      }
      /**
       * <code>optional int32 flag = 4;</code>
       */
      public Builder setFlag(int value) {
        bitField0_ |= 0x00000008;
        flag_ = value;
        
        return this;
      }
      /**
       * <code>optional int32 flag = 4;</code>
       */
      public Builder clearFlag() {
        bitField0_ = (bitField0_ & ~0x00000008);
        flag_ = 0;
        
        return this;
      }

      // optional int64 gid = 5;
      private long gid_ ;
      /**
       * <code>optional int64 gid = 5;</code>
       *
       * <pre>
       *for resp
       * </pre>
       */
      public boolean hasGid() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int64 gid = 5;</code>
       *
       * <pre>
       *for resp
       * </pre>
       */
      public long getGid() {
        return gid_;
      }
      /**
       * <code>optional int64 gid = 5;</code>
       *
       * <pre>
       *for resp
       * </pre>
       */
      public Builder setGid(long value) {
        bitField0_ |= 0x00000010;
        gid_ = value;
        
        return this;
      }
      /**
       * <code>optional int64 gid = 5;</code>
       *
       * <pre>
       *for resp
       * </pre>
       */
      public Builder clearGid() {
        bitField0_ = (bitField0_ & ~0x00000010);
        gid_ = 0L;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.jpush.im.protobuf.CreateGroup)
    }

    static {
      defaultInstance = new CreateGroup(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.jpush.im.protobuf.CreateGroup)
  }

  public interface ExitGroupOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // optional int64 gid = 1;
    /**
     * <code>optional int64 gid = 1;</code>
     */
    boolean hasGid();
    /**
     * <code>optional int64 gid = 1;</code>
     */
    long getGid();
  }
  /**
   * Protobuf type {@code com.jpush.im.protobuf.ExitGroup}
   *
   * <pre>
   * cmd = 9
   * </pre>
   */
  public static final class ExitGroup extends
      com.google.protobuf.GeneratedMessageLite
      implements ExitGroupOrBuilder {
    // Use ExitGroup.newBuilder() to construct.
    private ExitGroup(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private ExitGroup(boolean noInit) {}

    private static final ExitGroup defaultInstance;
    public static ExitGroup getDefaultInstance() {
      return defaultInstance;
    }

    public ExitGroup getDefaultInstanceForType() {
      return defaultInstance;
    }

    private ExitGroup(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              gid_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<ExitGroup> PARSER =
        new com.google.protobuf.AbstractParser<ExitGroup>() {
      public ExitGroup parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExitGroup(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ExitGroup> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 gid = 1;
    public static final int GID_FIELD_NUMBER = 1;
    private long gid_;
    /**
     * <code>optional int64 gid = 1;</code>
     */
    public boolean hasGid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 gid = 1;</code>
     */
    public long getGid() {
      return gid_;
    }

    private void initFields() {
      gid_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, gid_);
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, gid_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.jpush.protobuf.Group.ExitGroup parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jpush.protobuf.Group.ExitGroup parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jpush.protobuf.Group.ExitGroup parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jpush.protobuf.Group.ExitGroup parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jpush.protobuf.Group.ExitGroup parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jpush.protobuf.Group.ExitGroup parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.jpush.protobuf.Group.ExitGroup parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.jpush.protobuf.Group.ExitGroup parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.jpush.protobuf.Group.ExitGroup parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jpush.protobuf.Group.ExitGroup parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.jpush.protobuf.Group.ExitGroup prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code com.jpush.im.protobuf.ExitGroup}
     *
     * <pre>
     * cmd = 9
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.jpush.protobuf.Group.ExitGroup, Builder>
        implements com.jpush.protobuf.Group.ExitGroupOrBuilder {
      // Construct using com.jpush.im.protobuf.Group.ExitGroup.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        gid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.jpush.protobuf.Group.ExitGroup getDefaultInstanceForType() {
        return com.jpush.protobuf.Group.ExitGroup.getDefaultInstance();
      }

      public com.jpush.protobuf.Group.ExitGroup build() {
        com.jpush.protobuf.Group.ExitGroup result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.jpush.protobuf.Group.ExitGroup buildPartial() {
        com.jpush.protobuf.Group.ExitGroup result = new com.jpush.protobuf.Group.ExitGroup(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.gid_ = gid_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.jpush.protobuf.Group.ExitGroup other) {
        if (other == com.jpush.protobuf.Group.ExitGroup.getDefaultInstance()) return this;
        if (other.hasGid()) {
          setGid(other.getGid());
        }
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jpush.protobuf.Group.ExitGroup parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jpush.protobuf.Group.ExitGroup) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 gid = 1;
      private long gid_ ;
      /**
       * <code>optional int64 gid = 1;</code>
       */
      public boolean hasGid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 gid = 1;</code>
       */
      public long getGid() {
        return gid_;
      }
      /**
       * <code>optional int64 gid = 1;</code>
       */
      public Builder setGid(long value) {
        bitField0_ |= 0x00000001;
        gid_ = value;
        
        return this;
      }
      /**
       * <code>optional int64 gid = 1;</code>
       */
      public Builder clearGid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        gid_ = 0L;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.jpush.im.protobuf.ExitGroup)
    }

    static {
      defaultInstance = new ExitGroup(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.jpush.im.protobuf.ExitGroup)
  }

  public interface AddGroupMemberOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // optional int64 gid = 1;
    /**
     * <code>optional int64 gid = 1;</code>
     */
    boolean hasGid();
    /**
     * <code>optional int64 gid = 1;</code>
     */
    long getGid();

    // optional int32 member_count = 2;
    /**
     * <code>optional int32 member_count = 2;</code>
     */
    boolean hasMemberCount();
    /**
     * <code>optional int32 member_count = 2;</code>
     */
    int getMemberCount();

    // repeated int64 member_uidlist = 3;
    /**
     * <code>repeated int64 member_uidlist = 3;</code>
     */
    java.util.List<java.lang.Long> getMemberUidlistList();
    /**
     * <code>repeated int64 member_uidlist = 3;</code>
     */
    int getMemberUidlistCount();
    /**
     * <code>repeated int64 member_uidlist = 3;</code>
     */
    long getMemberUidlist(int index);
  }
  /**
   * Protobuf type {@code com.jpush.im.protobuf.AddGroupMember}
   *
   * <pre>
   * cmd = 10
   * </pre>
   */
  public static final class AddGroupMember extends
      com.google.protobuf.GeneratedMessageLite
      implements AddGroupMemberOrBuilder {
    // Use AddGroupMember.newBuilder() to construct.
    private AddGroupMember(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private AddGroupMember(boolean noInit) {}

    private static final AddGroupMember defaultInstance;
    public static AddGroupMember getDefaultInstance() {
      return defaultInstance;
    }

    public AddGroupMember getDefaultInstanceForType() {
      return defaultInstance;
    }

    private AddGroupMember(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              gid_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              memberCount_ = input.readInt32();
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                memberUidlist_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000004;
              }
              memberUidlist_.add(input.readInt64());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                memberUidlist_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                memberUidlist_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          memberUidlist_ = java.util.Collections.unmodifiableList(memberUidlist_);
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<AddGroupMember> PARSER =
        new com.google.protobuf.AbstractParser<AddGroupMember>() {
      public AddGroupMember parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AddGroupMember(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AddGroupMember> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 gid = 1;
    public static final int GID_FIELD_NUMBER = 1;
    private long gid_;
    /**
     * <code>optional int64 gid = 1;</code>
     */
    public boolean hasGid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 gid = 1;</code>
     */
    public long getGid() {
      return gid_;
    }

    // optional int32 member_count = 2;
    public static final int MEMBER_COUNT_FIELD_NUMBER = 2;
    private int memberCount_;
    /**
     * <code>optional int32 member_count = 2;</code>
     */
    public boolean hasMemberCount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 member_count = 2;</code>
     */
    public int getMemberCount() {
      return memberCount_;
    }

    // repeated int64 member_uidlist = 3;
    public static final int MEMBER_UIDLIST_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Long> memberUidlist_;
    /**
     * <code>repeated int64 member_uidlist = 3;</code>
     */
    public java.util.List<java.lang.Long>
        getMemberUidlistList() {
      return memberUidlist_;
    }
    /**
     * <code>repeated int64 member_uidlist = 3;</code>
     */
    public int getMemberUidlistCount() {
      return memberUidlist_.size();
    }
    /**
     * <code>repeated int64 member_uidlist = 3;</code>
     */
    public long getMemberUidlist(int index) {
      return memberUidlist_.get(index);
    }

    private void initFields() {
      gid_ = 0L;
      memberCount_ = 0;
      memberUidlist_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, gid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, memberCount_);
      }
      for (int i = 0; i < memberUidlist_.size(); i++) {
        output.writeInt64(3, memberUidlist_.get(i));
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, gid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, memberCount_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < memberUidlist_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(memberUidlist_.get(i));
        }
        size += dataSize;
        size += 1 * getMemberUidlistList().size();
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.jpush.protobuf.Group.AddGroupMember parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jpush.protobuf.Group.AddGroupMember parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jpush.protobuf.Group.AddGroupMember parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jpush.protobuf.Group.AddGroupMember parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jpush.protobuf.Group.AddGroupMember parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jpush.protobuf.Group.AddGroupMember parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.jpush.protobuf.Group.AddGroupMember parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.jpush.protobuf.Group.AddGroupMember parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.jpush.protobuf.Group.AddGroupMember parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jpush.protobuf.Group.AddGroupMember parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.jpush.protobuf.Group.AddGroupMember prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code com.jpush.im.protobuf.AddGroupMember}
     *
     * <pre>
     * cmd = 10
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.jpush.protobuf.Group.AddGroupMember, Builder>
        implements com.jpush.protobuf.Group.AddGroupMemberOrBuilder {
      // Construct using com.jpush.im.protobuf.Group.AddGroupMember.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        gid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        memberCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        memberUidlist_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.jpush.protobuf.Group.AddGroupMember getDefaultInstanceForType() {
        return com.jpush.protobuf.Group.AddGroupMember.getDefaultInstance();
      }

      public com.jpush.protobuf.Group.AddGroupMember build() {
        com.jpush.protobuf.Group.AddGroupMember result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.jpush.protobuf.Group.AddGroupMember buildPartial() {
        com.jpush.protobuf.Group.AddGroupMember result = new com.jpush.protobuf.Group.AddGroupMember(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.gid_ = gid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.memberCount_ = memberCount_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          memberUidlist_ = java.util.Collections.unmodifiableList(memberUidlist_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.memberUidlist_ = memberUidlist_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.jpush.protobuf.Group.AddGroupMember other) {
        if (other == com.jpush.protobuf.Group.AddGroupMember.getDefaultInstance()) return this;
        if (other.hasGid()) {
          setGid(other.getGid());
        }
        if (other.hasMemberCount()) {
          setMemberCount(other.getMemberCount());
        }
        if (!other.memberUidlist_.isEmpty()) {
          if (memberUidlist_.isEmpty()) {
            memberUidlist_ = other.memberUidlist_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureMemberUidlistIsMutable();
            memberUidlist_.addAll(other.memberUidlist_);
          }
          
        }
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jpush.protobuf.Group.AddGroupMember parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jpush.protobuf.Group.AddGroupMember) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 gid = 1;
      private long gid_ ;
      /**
       * <code>optional int64 gid = 1;</code>
       */
      public boolean hasGid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 gid = 1;</code>
       */
      public long getGid() {
        return gid_;
      }
      /**
       * <code>optional int64 gid = 1;</code>
       */
      public Builder setGid(long value) {
        bitField0_ |= 0x00000001;
        gid_ = value;
        
        return this;
      }
      /**
       * <code>optional int64 gid = 1;</code>
       */
      public Builder clearGid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        gid_ = 0L;
        
        return this;
      }

      // optional int32 member_count = 2;
      private int memberCount_ ;
      /**
       * <code>optional int32 member_count = 2;</code>
       */
      public boolean hasMemberCount() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 member_count = 2;</code>
       */
      public int getMemberCount() {
        return memberCount_;
      }
      /**
       * <code>optional int32 member_count = 2;</code>
       */
      public Builder setMemberCount(int value) {
        bitField0_ |= 0x00000002;
        memberCount_ = value;
        
        return this;
      }
      /**
       * <code>optional int32 member_count = 2;</code>
       */
      public Builder clearMemberCount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        memberCount_ = 0;
        
        return this;
      }

      // repeated int64 member_uidlist = 3;
      private java.util.List<java.lang.Long> memberUidlist_ = java.util.Collections.emptyList();
      private void ensureMemberUidlistIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          memberUidlist_ = new java.util.ArrayList<java.lang.Long>(memberUidlist_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated int64 member_uidlist = 3;</code>
       */
      public java.util.List<java.lang.Long>
          getMemberUidlistList() {
        return java.util.Collections.unmodifiableList(memberUidlist_);
      }
      /**
       * <code>repeated int64 member_uidlist = 3;</code>
       */
      public int getMemberUidlistCount() {
        return memberUidlist_.size();
      }
      /**
       * <code>repeated int64 member_uidlist = 3;</code>
       */
      public long getMemberUidlist(int index) {
        return memberUidlist_.get(index);
      }
      /**
       * <code>repeated int64 member_uidlist = 3;</code>
       */
      public Builder setMemberUidlist(
          int index, long value) {
        ensureMemberUidlistIsMutable();
        memberUidlist_.set(index, value);
        
        return this;
      }
      /**
       * <code>repeated int64 member_uidlist = 3;</code>
       */
      public Builder addMemberUidlist(long value) {
        ensureMemberUidlistIsMutable();
        memberUidlist_.add(value);
        
        return this;
      }
      /**
       * <code>repeated int64 member_uidlist = 3;</code>
       */
      public Builder addAllMemberUidlist(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureMemberUidlistIsMutable();
        super.addAll(values, memberUidlist_);
        
        return this;
      }
      /**
       * <code>repeated int64 member_uidlist = 3;</code>
       */
      public Builder clearMemberUidlist() {
        memberUidlist_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.jpush.im.protobuf.AddGroupMember)
    }

    static {
      defaultInstance = new AddGroupMember(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.jpush.im.protobuf.AddGroupMember)
  }

  public interface DelGroupMemberOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // optional int64 gid = 1;
    /**
     * <code>optional int64 gid = 1;</code>
     */
    boolean hasGid();
    /**
     * <code>optional int64 gid = 1;</code>
     */
    long getGid();

    // optional int32 member_count = 2;
    /**
     * <code>optional int32 member_count = 2;</code>
     */
    boolean hasMemberCount();
    /**
     * <code>optional int32 member_count = 2;</code>
     */
    int getMemberCount();

    // repeated int64 member_uidlist = 3;
    /**
     * <code>repeated int64 member_uidlist = 3;</code>
     */
    java.util.List<java.lang.Long> getMemberUidlistList();
    /**
     * <code>repeated int64 member_uidlist = 3;</code>
     */
    int getMemberUidlistCount();
    /**
     * <code>repeated int64 member_uidlist = 3;</code>
     */
    long getMemberUidlist(int index);
  }
  /**
   * Protobuf type {@code com.jpush.im.protobuf.DelGroupMember}
   *
   * <pre>
   * cmd = 11
   * </pre>
   */
  public static final class DelGroupMember extends
      com.google.protobuf.GeneratedMessageLite
      implements DelGroupMemberOrBuilder {
    // Use DelGroupMember.newBuilder() to construct.
    private DelGroupMember(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private DelGroupMember(boolean noInit) {}

    private static final DelGroupMember defaultInstance;
    public static DelGroupMember getDefaultInstance() {
      return defaultInstance;
    }

    public DelGroupMember getDefaultInstanceForType() {
      return defaultInstance;
    }

    private DelGroupMember(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              gid_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              memberCount_ = input.readInt32();
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                memberUidlist_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000004;
              }
              memberUidlist_.add(input.readInt64());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                memberUidlist_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                memberUidlist_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          memberUidlist_ = java.util.Collections.unmodifiableList(memberUidlist_);
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<DelGroupMember> PARSER =
        new com.google.protobuf.AbstractParser<DelGroupMember>() {
      public DelGroupMember parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DelGroupMember(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DelGroupMember> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 gid = 1;
    public static final int GID_FIELD_NUMBER = 1;
    private long gid_;
    /**
     * <code>optional int64 gid = 1;</code>
     */
    public boolean hasGid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 gid = 1;</code>
     */
    public long getGid() {
      return gid_;
    }

    // optional int32 member_count = 2;
    public static final int MEMBER_COUNT_FIELD_NUMBER = 2;
    private int memberCount_;
    /**
     * <code>optional int32 member_count = 2;</code>
     */
    public boolean hasMemberCount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 member_count = 2;</code>
     */
    public int getMemberCount() {
      return memberCount_;
    }

    // repeated int64 member_uidlist = 3;
    public static final int MEMBER_UIDLIST_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Long> memberUidlist_;
    /**
     * <code>repeated int64 member_uidlist = 3;</code>
     */
    public java.util.List<java.lang.Long>
        getMemberUidlistList() {
      return memberUidlist_;
    }
    /**
     * <code>repeated int64 member_uidlist = 3;</code>
     */
    public int getMemberUidlistCount() {
      return memberUidlist_.size();
    }
    /**
     * <code>repeated int64 member_uidlist = 3;</code>
     */
    public long getMemberUidlist(int index) {
      return memberUidlist_.get(index);
    }

    private void initFields() {
      gid_ = 0L;
      memberCount_ = 0;
      memberUidlist_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, gid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, memberCount_);
      }
      for (int i = 0; i < memberUidlist_.size(); i++) {
        output.writeInt64(3, memberUidlist_.get(i));
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, gid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, memberCount_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < memberUidlist_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(memberUidlist_.get(i));
        }
        size += dataSize;
        size += 1 * getMemberUidlistList().size();
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.jpush.protobuf.Group.DelGroupMember parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jpush.protobuf.Group.DelGroupMember parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jpush.protobuf.Group.DelGroupMember parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jpush.protobuf.Group.DelGroupMember parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jpush.protobuf.Group.DelGroupMember parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jpush.protobuf.Group.DelGroupMember parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.jpush.protobuf.Group.DelGroupMember parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.jpush.protobuf.Group.DelGroupMember parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.jpush.protobuf.Group.DelGroupMember parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jpush.protobuf.Group.DelGroupMember parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.jpush.protobuf.Group.DelGroupMember prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code com.jpush.im.protobuf.DelGroupMember}
     *
     * <pre>
     * cmd = 11
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.jpush.protobuf.Group.DelGroupMember, Builder>
        implements com.jpush.protobuf.Group.DelGroupMemberOrBuilder {
      // Construct using com.jpush.im.protobuf.Group.DelGroupMember.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        gid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        memberCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        memberUidlist_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.jpush.protobuf.Group.DelGroupMember getDefaultInstanceForType() {
        return com.jpush.protobuf.Group.DelGroupMember.getDefaultInstance();
      }

      public com.jpush.protobuf.Group.DelGroupMember build() {
        com.jpush.protobuf.Group.DelGroupMember result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.jpush.protobuf.Group.DelGroupMember buildPartial() {
        com.jpush.protobuf.Group.DelGroupMember result = new com.jpush.protobuf.Group.DelGroupMember(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.gid_ = gid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.memberCount_ = memberCount_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          memberUidlist_ = java.util.Collections.unmodifiableList(memberUidlist_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.memberUidlist_ = memberUidlist_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.jpush.protobuf.Group.DelGroupMember other) {
        if (other == com.jpush.protobuf.Group.DelGroupMember.getDefaultInstance()) return this;
        if (other.hasGid()) {
          setGid(other.getGid());
        }
        if (other.hasMemberCount()) {
          setMemberCount(other.getMemberCount());
        }
        if (!other.memberUidlist_.isEmpty()) {
          if (memberUidlist_.isEmpty()) {
            memberUidlist_ = other.memberUidlist_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureMemberUidlistIsMutable();
            memberUidlist_.addAll(other.memberUidlist_);
          }
          
        }
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jpush.protobuf.Group.DelGroupMember parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jpush.protobuf.Group.DelGroupMember) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 gid = 1;
      private long gid_ ;
      /**
       * <code>optional int64 gid = 1;</code>
       */
      public boolean hasGid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 gid = 1;</code>
       */
      public long getGid() {
        return gid_;
      }
      /**
       * <code>optional int64 gid = 1;</code>
       */
      public Builder setGid(long value) {
        bitField0_ |= 0x00000001;
        gid_ = value;
        
        return this;
      }
      /**
       * <code>optional int64 gid = 1;</code>
       */
      public Builder clearGid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        gid_ = 0L;
        
        return this;
      }

      // optional int32 member_count = 2;
      private int memberCount_ ;
      /**
       * <code>optional int32 member_count = 2;</code>
       */
      public boolean hasMemberCount() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 member_count = 2;</code>
       */
      public int getMemberCount() {
        return memberCount_;
      }
      /**
       * <code>optional int32 member_count = 2;</code>
       */
      public Builder setMemberCount(int value) {
        bitField0_ |= 0x00000002;
        memberCount_ = value;
        
        return this;
      }
      /**
       * <code>optional int32 member_count = 2;</code>
       */
      public Builder clearMemberCount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        memberCount_ = 0;
        
        return this;
      }

      // repeated int64 member_uidlist = 3;
      private java.util.List<java.lang.Long> memberUidlist_ = java.util.Collections.emptyList();
      private void ensureMemberUidlistIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          memberUidlist_ = new java.util.ArrayList<java.lang.Long>(memberUidlist_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated int64 member_uidlist = 3;</code>
       */
      public java.util.List<java.lang.Long>
          getMemberUidlistList() {
        return java.util.Collections.unmodifiableList(memberUidlist_);
      }
      /**
       * <code>repeated int64 member_uidlist = 3;</code>
       */
      public int getMemberUidlistCount() {
        return memberUidlist_.size();
      }
      /**
       * <code>repeated int64 member_uidlist = 3;</code>
       */
      public long getMemberUidlist(int index) {
        return memberUidlist_.get(index);
      }
      /**
       * <code>repeated int64 member_uidlist = 3;</code>
       */
      public Builder setMemberUidlist(
          int index, long value) {
        ensureMemberUidlistIsMutable();
        memberUidlist_.set(index, value);
        
        return this;
      }
      /**
       * <code>repeated int64 member_uidlist = 3;</code>
       */
      public Builder addMemberUidlist(long value) {
        ensureMemberUidlistIsMutable();
        memberUidlist_.add(value);
        
        return this;
      }
      /**
       * <code>repeated int64 member_uidlist = 3;</code>
       */
      public Builder addAllMemberUidlist(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureMemberUidlistIsMutable();
        super.addAll(values, memberUidlist_);
        
        return this;
      }
      /**
       * <code>repeated int64 member_uidlist = 3;</code>
       */
      public Builder clearMemberUidlist() {
        memberUidlist_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.jpush.im.protobuf.DelGroupMember)
    }

    static {
      defaultInstance = new DelGroupMember(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.jpush.im.protobuf.DelGroupMember)
  }

  public interface UpdateGroupInfoOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // optional int64 gid = 1;
    /**
     * <code>optional int64 gid = 1;</code>
     */
    boolean hasGid();
    /**
     * <code>optional int64 gid = 1;</code>
     */
    long getGid();

    // optional string name = 2;
    /**
     * <code>optional string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // optional string info = 3;
    /**
     * <code>optional string info = 3;</code>
     */
    boolean hasInfo();
    /**
     * <code>optional string info = 3;</code>
     */
    java.lang.String getInfo();
    /**
     * <code>optional string info = 3;</code>
     */
    com.google.protobuf.ByteString
        getInfoBytes();
  }
  /**
   * Protobuf type {@code com.jpush.im.protobuf.UpdateGroupInfo}
   *
   * <pre>
   * cmd = 12
   * </pre>
   */
  public static final class UpdateGroupInfo extends
      com.google.protobuf.GeneratedMessageLite
      implements UpdateGroupInfoOrBuilder {
    // Use UpdateGroupInfo.newBuilder() to construct.
    private UpdateGroupInfo(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private UpdateGroupInfo(boolean noInit) {}

    private static final UpdateGroupInfo defaultInstance;
    public static UpdateGroupInfo getDefaultInstance() {
      return defaultInstance;
    }

    public UpdateGroupInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private UpdateGroupInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              gid_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              info_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<UpdateGroupInfo> PARSER =
        new com.google.protobuf.AbstractParser<UpdateGroupInfo>() {
      public UpdateGroupInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UpdateGroupInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<UpdateGroupInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 gid = 1;
    public static final int GID_FIELD_NUMBER = 1;
    private long gid_;
    /**
     * <code>optional int64 gid = 1;</code>
     */
    public boolean hasGid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 gid = 1;</code>
     */
    public long getGid() {
      return gid_;
    }

    // optional string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string info = 3;
    public static final int INFO_FIELD_NUMBER = 3;
    private java.lang.Object info_;
    /**
     * <code>optional string info = 3;</code>
     */
    public boolean hasInfo() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string info = 3;</code>
     */
    public java.lang.String getInfo() {
      java.lang.Object ref = info_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          info_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string info = 3;</code>
     */
    public com.google.protobuf.ByteString
        getInfoBytes() {
      java.lang.Object ref = info_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        info_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      gid_ = 0L;
      name_ = "";
      info_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, gid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getInfoBytes());
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, gid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getInfoBytes());
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.jpush.protobuf.Group.UpdateGroupInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jpush.protobuf.Group.UpdateGroupInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jpush.protobuf.Group.UpdateGroupInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jpush.protobuf.Group.UpdateGroupInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jpush.protobuf.Group.UpdateGroupInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jpush.protobuf.Group.UpdateGroupInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.jpush.protobuf.Group.UpdateGroupInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.jpush.protobuf.Group.UpdateGroupInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.jpush.protobuf.Group.UpdateGroupInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jpush.protobuf.Group.UpdateGroupInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.jpush.protobuf.Group.UpdateGroupInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code com.jpush.im.protobuf.UpdateGroupInfo}
     *
     * <pre>
     * cmd = 12
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.jpush.protobuf.Group.UpdateGroupInfo, Builder>
        implements com.jpush.protobuf.Group.UpdateGroupInfoOrBuilder {
      // Construct using com.jpush.im.protobuf.Group.UpdateGroupInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        gid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        info_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.jpush.protobuf.Group.UpdateGroupInfo getDefaultInstanceForType() {
        return com.jpush.protobuf.Group.UpdateGroupInfo.getDefaultInstance();
      }

      public com.jpush.protobuf.Group.UpdateGroupInfo build() {
        com.jpush.protobuf.Group.UpdateGroupInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.jpush.protobuf.Group.UpdateGroupInfo buildPartial() {
        com.jpush.protobuf.Group.UpdateGroupInfo result = new com.jpush.protobuf.Group.UpdateGroupInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.gid_ = gid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.info_ = info_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.jpush.protobuf.Group.UpdateGroupInfo other) {
        if (other == com.jpush.protobuf.Group.UpdateGroupInfo.getDefaultInstance()) return this;
        if (other.hasGid()) {
          setGid(other.getGid());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          
        }
        if (other.hasInfo()) {
          bitField0_ |= 0x00000004;
          info_ = other.info_;
          
        }
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jpush.protobuf.Group.UpdateGroupInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jpush.protobuf.Group.UpdateGroupInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 gid = 1;
      private long gid_ ;
      /**
       * <code>optional int64 gid = 1;</code>
       */
      public boolean hasGid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 gid = 1;</code>
       */
      public long getGid() {
        return gid_;
      }
      /**
       * <code>optional int64 gid = 1;</code>
       */
      public Builder setGid(long value) {
        bitField0_ |= 0x00000001;
        gid_ = value;
        
        return this;
      }
      /**
       * <code>optional int64 gid = 1;</code>
       */
      public Builder clearGid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        gid_ = 0L;
        
        return this;
      }

      // optional string name = 2;
      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        
        return this;
      }

      // optional string info = 3;
      private java.lang.Object info_ = "";
      /**
       * <code>optional string info = 3;</code>
       */
      public boolean hasInfo() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string info = 3;</code>
       */
      public java.lang.String getInfo() {
        java.lang.Object ref = info_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          info_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string info = 3;</code>
       */
      public com.google.protobuf.ByteString
          getInfoBytes() {
        java.lang.Object ref = info_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          info_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string info = 3;</code>
       */
      public Builder setInfo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        info_ = value;
        
        return this;
      }
      /**
       * <code>optional string info = 3;</code>
       */
      public Builder clearInfo() {
        bitField0_ = (bitField0_ & ~0x00000004);
        info_ = getDefaultInstance().getInfo();
        
        return this;
      }
      /**
       * <code>optional string info = 3;</code>
       */
      public Builder setInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        info_ = value;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.jpush.im.protobuf.UpdateGroupInfo)
    }

    static {
      defaultInstance = new UpdateGroupInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.jpush.im.protobuf.UpdateGroupInfo)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
