// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.jpush.protobuf;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface MessageContentOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // optional string text = 1;
    /**
     * <code>optional string text = 1;</code>
     */
    boolean hasText();
    /**
     * <code>optional string text = 1;</code>
     */
    java.lang.String getText();
    /**
     * <code>optional string text = 1;</code>
     */
    com.google.protobuf.ByteString
        getTextBytes();
  }
  /**
   * Protobuf type {@code com.jpush.im.protobuf.MessageContent}
   */
  public static final class MessageContent extends
      com.google.protobuf.GeneratedMessageLite
      implements MessageContentOrBuilder {
    // Use MessageContent.newBuilder() to construct.
    private MessageContent(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private MessageContent(boolean noInit) {}

    private static final MessageContent defaultInstance;
    public static MessageContent getDefaultInstance() {
      return defaultInstance;
    }

    public MessageContent getDefaultInstanceForType() {
      return defaultInstance;
    }

    private MessageContent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              text_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<MessageContent> PARSER =
        new com.google.protobuf.AbstractParser<MessageContent>() {
      public MessageContent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageContent(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MessageContent> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string text = 1;
    public static final int TEXT_FIELD_NUMBER = 1;
    private java.lang.Object text_;
    /**
     * <code>optional string text = 1;</code>
     */
    public boolean hasText() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string text = 1;</code>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          text_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string text = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      text_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTextBytes());
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTextBytes());
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.jpush.protobuf.Message.MessageContent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jpush.protobuf.Message.MessageContent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jpush.protobuf.Message.MessageContent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jpush.protobuf.Message.MessageContent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jpush.protobuf.Message.MessageContent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jpush.protobuf.Message.MessageContent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.jpush.protobuf.Message.MessageContent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.jpush.protobuf.Message.MessageContent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.jpush.protobuf.Message.MessageContent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jpush.protobuf.Message.MessageContent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.jpush.protobuf.Message.MessageContent prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code com.jpush.im.protobuf.MessageContent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.jpush.protobuf.Message.MessageContent, Builder>
        implements com.jpush.protobuf.Message.MessageContentOrBuilder {
      // Construct using com.jpush.im.protobuf.Message.MessageContent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.jpush.protobuf.Message.MessageContent getDefaultInstanceForType() {
        return com.jpush.protobuf.Message.MessageContent.getDefaultInstance();
      }

      public com.jpush.protobuf.Message.MessageContent build() {
        com.jpush.protobuf.Message.MessageContent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.jpush.protobuf.Message.MessageContent buildPartial() {
        com.jpush.protobuf.Message.MessageContent result = new com.jpush.protobuf.Message.MessageContent(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.text_ = text_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.jpush.protobuf.Message.MessageContent other) {
        if (other == com.jpush.protobuf.Message.MessageContent.getDefaultInstance()) return this;
        if (other.hasText()) {
          bitField0_ |= 0x00000001;
          text_ = other.text_;
          
        }
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jpush.protobuf.Message.MessageContent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jpush.protobuf.Message.MessageContent) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string text = 1;
      private java.lang.Object text_ = "";
      /**
       * <code>optional string text = 1;</code>
       */
      public boolean hasText() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string text = 1;</code>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string text = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string text = 1;</code>
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        text_ = value;
        
        return this;
      }
      /**
       * <code>optional string text = 1;</code>
       */
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000001);
        text_ = getDefaultInstance().getText();
        
        return this;
      }
      /**
       * <code>optional string text = 1;</code>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        text_ = value;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.jpush.im.protobuf.MessageContent)
    }

    static {
      defaultInstance = new MessageContent(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.jpush.im.protobuf.MessageContent)
  }

  public interface SingleMsgOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // optional int64 target_uid = 1;
    /**
     * <code>optional int64 target_uid = 1;</code>
     */
    boolean hasTargetUid();
    /**
     * <code>optional int64 target_uid = 1;</code>
     */
    long getTargetUid();

    // optional .com.jpush.im.protobuf.MessageContent content = 2;
    /**
     * <code>optional .com.jpush.im.protobuf.MessageContent content = 2;</code>
     */
    boolean hasContent();
    /**
     * <code>optional .com.jpush.im.protobuf.MessageContent content = 2;</code>
     */
    com.jpush.protobuf.Message.MessageContent getContent();

    // optional int64 msgid = 3;
    /**
     * <code>optional int64 msgid = 3;</code>
     *
     * <pre>
     *for resp 
     * </pre>
     */
    boolean hasMsgid();
    /**
     * <code>optional int64 msgid = 3;</code>
     *
     * <pre>
     *for resp 
     * </pre>
     */
    long getMsgid();
  }
  /**
   * Protobuf type {@code com.jpush.im.protobuf.SingleMsg}
   *
   * <pre>
   * cmd = 3 
   * </pre>
   */
  public static final class SingleMsg extends
      com.google.protobuf.GeneratedMessageLite
      implements SingleMsgOrBuilder {
    // Use SingleMsg.newBuilder() to construct.
    private SingleMsg(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private SingleMsg(boolean noInit) {}

    private static final SingleMsg defaultInstance;
    public static SingleMsg getDefaultInstance() {
      return defaultInstance;
    }

    public SingleMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private SingleMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              targetUid_ = input.readInt64();
              break;
            }
            case 18: {
              com.jpush.protobuf.Message.MessageContent.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = content_.toBuilder();
              }
              content_ = input.readMessage(com.jpush.protobuf.Message.MessageContent.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(content_);
                content_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              msgid_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<SingleMsg> PARSER =
        new com.google.protobuf.AbstractParser<SingleMsg>() {
      public SingleMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SingleMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SingleMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 target_uid = 1;
    public static final int TARGET_UID_FIELD_NUMBER = 1;
    private long targetUid_;
    /**
     * <code>optional int64 target_uid = 1;</code>
     */
    public boolean hasTargetUid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 target_uid = 1;</code>
     */
    public long getTargetUid() {
      return targetUid_;
    }

    // optional .com.jpush.im.protobuf.MessageContent content = 2;
    public static final int CONTENT_FIELD_NUMBER = 2;
    private com.jpush.protobuf.Message.MessageContent content_;
    /**
     * <code>optional .com.jpush.im.protobuf.MessageContent content = 2;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .com.jpush.im.protobuf.MessageContent content = 2;</code>
     */
    public com.jpush.protobuf.Message.MessageContent getContent() {
      return content_;
    }

    // optional int64 msgid = 3;
    public static final int MSGID_FIELD_NUMBER = 3;
    private long msgid_;
    /**
     * <code>optional int64 msgid = 3;</code>
     *
     * <pre>
     *for resp 
     * </pre>
     */
    public boolean hasMsgid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 msgid = 3;</code>
     *
     * <pre>
     *for resp 
     * </pre>
     */
    public long getMsgid() {
      return msgid_;
    }

    private void initFields() {
      targetUid_ = 0L;
      content_ = com.jpush.protobuf.Message.MessageContent.getDefaultInstance();
      msgid_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, targetUid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, content_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, msgid_);
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, targetUid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, content_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, msgid_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.jpush.protobuf.Message.SingleMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jpush.protobuf.Message.SingleMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jpush.protobuf.Message.SingleMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jpush.protobuf.Message.SingleMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jpush.protobuf.Message.SingleMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jpush.protobuf.Message.SingleMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.jpush.protobuf.Message.SingleMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.jpush.protobuf.Message.SingleMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.jpush.protobuf.Message.SingleMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jpush.protobuf.Message.SingleMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.jpush.protobuf.Message.SingleMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code com.jpush.im.protobuf.SingleMsg}
     *
     * <pre>
     * cmd = 3 
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.jpush.protobuf.Message.SingleMsg, Builder>
        implements com.jpush.protobuf.Message.SingleMsgOrBuilder {
      // Construct using com.jpush.im.protobuf.Message.SingleMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        targetUid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        content_ = com.jpush.protobuf.Message.MessageContent.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000002);
        msgid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.jpush.protobuf.Message.SingleMsg getDefaultInstanceForType() {
        return com.jpush.protobuf.Message.SingleMsg.getDefaultInstance();
      }

      public com.jpush.protobuf.Message.SingleMsg build() {
        com.jpush.protobuf.Message.SingleMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.jpush.protobuf.Message.SingleMsg buildPartial() {
        com.jpush.protobuf.Message.SingleMsg result = new com.jpush.protobuf.Message.SingleMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.targetUid_ = targetUid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.content_ = content_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.msgid_ = msgid_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.jpush.protobuf.Message.SingleMsg other) {
        if (other == com.jpush.protobuf.Message.SingleMsg.getDefaultInstance()) return this;
        if (other.hasTargetUid()) {
          setTargetUid(other.getTargetUid());
        }
        if (other.hasContent()) {
          mergeContent(other.getContent());
        }
        if (other.hasMsgid()) {
          setMsgid(other.getMsgid());
        }
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jpush.protobuf.Message.SingleMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jpush.protobuf.Message.SingleMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 target_uid = 1;
      private long targetUid_ ;
      /**
       * <code>optional int64 target_uid = 1;</code>
       */
      public boolean hasTargetUid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 target_uid = 1;</code>
       */
      public long getTargetUid() {
        return targetUid_;
      }
      /**
       * <code>optional int64 target_uid = 1;</code>
       */
      public Builder setTargetUid(long value) {
        bitField0_ |= 0x00000001;
        targetUid_ = value;
        
        return this;
      }
      /**
       * <code>optional int64 target_uid = 1;</code>
       */
      public Builder clearTargetUid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        targetUid_ = 0L;
        
        return this;
      }

      // optional .com.jpush.im.protobuf.MessageContent content = 2;
      private com.jpush.protobuf.Message.MessageContent content_ = com.jpush.protobuf.Message.MessageContent.getDefaultInstance();
      /**
       * <code>optional .com.jpush.im.protobuf.MessageContent content = 2;</code>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .com.jpush.im.protobuf.MessageContent content = 2;</code>
       */
      public com.jpush.protobuf.Message.MessageContent getContent() {
        return content_;
      }
      /**
       * <code>optional .com.jpush.im.protobuf.MessageContent content = 2;</code>
       */
      public Builder setContent(com.jpush.protobuf.Message.MessageContent value) {
        if (value == null) {
          throw new NullPointerException();
        }
        content_ = value;

        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.jpush.im.protobuf.MessageContent content = 2;</code>
       */
      public Builder setContent(
          com.jpush.protobuf.Message.MessageContent.Builder builderForValue) {
        content_ = builderForValue.build();

        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.jpush.im.protobuf.MessageContent content = 2;</code>
       */
      public Builder mergeContent(com.jpush.protobuf.Message.MessageContent value) {
        if (((bitField0_ & 0x00000002) == 0x00000002) &&
            content_ != com.jpush.protobuf.Message.MessageContent.getDefaultInstance()) {
          content_ =
            com.jpush.protobuf.Message.MessageContent.newBuilder(content_).mergeFrom(value).buildPartial();
        } else {
          content_ = value;
        }

        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.jpush.im.protobuf.MessageContent content = 2;</code>
       */
      public Builder clearContent() {
        content_ = com.jpush.protobuf.Message.MessageContent.getDefaultInstance();

        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      // optional int64 msgid = 3;
      private long msgid_ ;
      /**
       * <code>optional int64 msgid = 3;</code>
       *
       * <pre>
       *for resp 
       * </pre>
       */
      public boolean hasMsgid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 msgid = 3;</code>
       *
       * <pre>
       *for resp 
       * </pre>
       */
      public long getMsgid() {
        return msgid_;
      }
      /**
       * <code>optional int64 msgid = 3;</code>
       *
       * <pre>
       *for resp 
       * </pre>
       */
      public Builder setMsgid(long value) {
        bitField0_ |= 0x00000004;
        msgid_ = value;
        
        return this;
      }
      /**
       * <code>optional int64 msgid = 3;</code>
       *
       * <pre>
       *for resp 
       * </pre>
       */
      public Builder clearMsgid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        msgid_ = 0L;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.jpush.im.protobuf.SingleMsg)
    }

    static {
      defaultInstance = new SingleMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.jpush.im.protobuf.SingleMsg)
  }

  public interface GroupMsgOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // optional int64 target_gid = 1;
    /**
     * <code>optional int64 target_gid = 1;</code>
     */
    boolean hasTargetGid();
    /**
     * <code>optional int64 target_gid = 1;</code>
     */
    long getTargetGid();

    // optional .com.jpush.im.protobuf.MessageContent content = 2;
    /**
     * <code>optional .com.jpush.im.protobuf.MessageContent content = 2;</code>
     */
    boolean hasContent();
    /**
     * <code>optional .com.jpush.im.protobuf.MessageContent content = 2;</code>
     */
    com.jpush.protobuf.Message.MessageContent getContent();

    // optional int64 msgid = 3;
    /**
     * <code>optional int64 msgid = 3;</code>
     *
     * <pre>
     *for resp 
     * </pre>
     */
    boolean hasMsgid();
    /**
     * <code>optional int64 msgid = 3;</code>
     *
     * <pre>
     *for resp 
     * </pre>
     */
    long getMsgid();
  }
  /**
   * Protobuf type {@code com.jpush.im.protobuf.GroupMsg}
   *
   * <pre>
   * cmd = 4 
   * </pre>
   */
  public static final class GroupMsg extends
      com.google.protobuf.GeneratedMessageLite
      implements GroupMsgOrBuilder {
    // Use GroupMsg.newBuilder() to construct.
    private GroupMsg(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private GroupMsg(boolean noInit) {}

    private static final GroupMsg defaultInstance;
    public static GroupMsg getDefaultInstance() {
      return defaultInstance;
    }

    public GroupMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private GroupMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              targetGid_ = input.readInt64();
              break;
            }
            case 18: {
              com.jpush.protobuf.Message.MessageContent.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = content_.toBuilder();
              }
              content_ = input.readMessage(com.jpush.protobuf.Message.MessageContent.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(content_);
                content_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              msgid_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<GroupMsg> PARSER =
        new com.google.protobuf.AbstractParser<GroupMsg>() {
      public GroupMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GroupMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GroupMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 target_gid = 1;
    public static final int TARGET_GID_FIELD_NUMBER = 1;
    private long targetGid_;
    /**
     * <code>optional int64 target_gid = 1;</code>
     */
    public boolean hasTargetGid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 target_gid = 1;</code>
     */
    public long getTargetGid() {
      return targetGid_;
    }

    // optional .com.jpush.im.protobuf.MessageContent content = 2;
    public static final int CONTENT_FIELD_NUMBER = 2;
    private com.jpush.protobuf.Message.MessageContent content_;
    /**
     * <code>optional .com.jpush.im.protobuf.MessageContent content = 2;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .com.jpush.im.protobuf.MessageContent content = 2;</code>
     */
    public com.jpush.protobuf.Message.MessageContent getContent() {
      return content_;
    }

    // optional int64 msgid = 3;
    public static final int MSGID_FIELD_NUMBER = 3;
    private long msgid_;
    /**
     * <code>optional int64 msgid = 3;</code>
     *
     * <pre>
     *for resp 
     * </pre>
     */
    public boolean hasMsgid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 msgid = 3;</code>
     *
     * <pre>
     *for resp 
     * </pre>
     */
    public long getMsgid() {
      return msgid_;
    }

    private void initFields() {
      targetGid_ = 0L;
      content_ = com.jpush.protobuf.Message.MessageContent.getDefaultInstance();
      msgid_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, targetGid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, content_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, msgid_);
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, targetGid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, content_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, msgid_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.jpush.protobuf.Message.GroupMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jpush.protobuf.Message.GroupMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jpush.protobuf.Message.GroupMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jpush.protobuf.Message.GroupMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jpush.protobuf.Message.GroupMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jpush.protobuf.Message.GroupMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.jpush.protobuf.Message.GroupMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.jpush.protobuf.Message.GroupMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.jpush.protobuf.Message.GroupMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.jpush.protobuf.Message.GroupMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.jpush.protobuf.Message.GroupMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code com.jpush.im.protobuf.GroupMsg}
     *
     * <pre>
     * cmd = 4 
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.jpush.protobuf.Message.GroupMsg, Builder>
        implements com.jpush.protobuf.Message.GroupMsgOrBuilder {
      // Construct using com.jpush.im.protobuf.Message.GroupMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        targetGid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        content_ = com.jpush.protobuf.Message.MessageContent.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000002);
        msgid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.jpush.protobuf.Message.GroupMsg getDefaultInstanceForType() {
        return com.jpush.protobuf.Message.GroupMsg.getDefaultInstance();
      }

      public com.jpush.protobuf.Message.GroupMsg build() {
        com.jpush.protobuf.Message.GroupMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.jpush.protobuf.Message.GroupMsg buildPartial() {
        com.jpush.protobuf.Message.GroupMsg result = new com.jpush.protobuf.Message.GroupMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.targetGid_ = targetGid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.content_ = content_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.msgid_ = msgid_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.jpush.protobuf.Message.GroupMsg other) {
        if (other == com.jpush.protobuf.Message.GroupMsg.getDefaultInstance()) return this;
        if (other.hasTargetGid()) {
          setTargetGid(other.getTargetGid());
        }
        if (other.hasContent()) {
          mergeContent(other.getContent());
        }
        if (other.hasMsgid()) {
          setMsgid(other.getMsgid());
        }
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jpush.protobuf.Message.GroupMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jpush.protobuf.Message.GroupMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 target_gid = 1;
      private long targetGid_ ;
      /**
       * <code>optional int64 target_gid = 1;</code>
       */
      public boolean hasTargetGid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 target_gid = 1;</code>
       */
      public long getTargetGid() {
        return targetGid_;
      }
      /**
       * <code>optional int64 target_gid = 1;</code>
       */
      public Builder setTargetGid(long value) {
        bitField0_ |= 0x00000001;
        targetGid_ = value;
        
        return this;
      }
      /**
       * <code>optional int64 target_gid = 1;</code>
       */
      public Builder clearTargetGid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        targetGid_ = 0L;
        
        return this;
      }

      // optional .com.jpush.im.protobuf.MessageContent content = 2;
      private com.jpush.protobuf.Message.MessageContent content_ = com.jpush.protobuf.Message.MessageContent.getDefaultInstance();
      /**
       * <code>optional .com.jpush.im.protobuf.MessageContent content = 2;</code>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .com.jpush.im.protobuf.MessageContent content = 2;</code>
       */
      public com.jpush.protobuf.Message.MessageContent getContent() {
        return content_;
      }
      /**
       * <code>optional .com.jpush.im.protobuf.MessageContent content = 2;</code>
       */
      public Builder setContent(com.jpush.protobuf.Message.MessageContent value) {
        if (value == null) {
          throw new NullPointerException();
        }
        content_ = value;

        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.jpush.im.protobuf.MessageContent content = 2;</code>
       */
      public Builder setContent(
          com.jpush.protobuf.Message.MessageContent.Builder builderForValue) {
        content_ = builderForValue.build();

        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.jpush.im.protobuf.MessageContent content = 2;</code>
       */
      public Builder mergeContent(com.jpush.protobuf.Message.MessageContent value) {
        if (((bitField0_ & 0x00000002) == 0x00000002) &&
            content_ != com.jpush.protobuf.Message.MessageContent.getDefaultInstance()) {
          content_ =
            com.jpush.protobuf.Message.MessageContent.newBuilder(content_).mergeFrom(value).buildPartial();
        } else {
          content_ = value;
        }

        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.jpush.im.protobuf.MessageContent content = 2;</code>
       */
      public Builder clearContent() {
        content_ = com.jpush.protobuf.Message.MessageContent.getDefaultInstance();

        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      // optional int64 msgid = 3;
      private long msgid_ ;
      /**
       * <code>optional int64 msgid = 3;</code>
       *
       * <pre>
       *for resp 
       * </pre>
       */
      public boolean hasMsgid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 msgid = 3;</code>
       *
       * <pre>
       *for resp 
       * </pre>
       */
      public long getMsgid() {
        return msgid_;
      }
      /**
       * <code>optional int64 msgid = 3;</code>
       *
       * <pre>
       *for resp 
       * </pre>
       */
      public Builder setMsgid(long value) {
        bitField0_ |= 0x00000004;
        msgid_ = value;
        
        return this;
      }
      /**
       * <code>optional int64 msgid = 3;</code>
       *
       * <pre>
       *for resp 
       * </pre>
       */
      public Builder clearMsgid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        msgid_ = 0L;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.jpush.im.protobuf.GroupMsg)
    }

    static {
      defaultInstance = new GroupMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.jpush.im.protobuf.GroupMsg)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
